name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-22.04
    steps:
      - name: install postgresql client
        run: | 
          sudo apt-get install -y postgresql-client
          psql --version  
      - name: connect to env
        env:
          PGPASSWORD: ${{ secrets.POSTGRES_ADMIN }}   
          PGHOST: ${{ secrets.POSTGRES_HOST }}  
        run: | 
          echo connecting to $PGHOST
          psql -p 5432 -d dev -U postgres -c 'select version();'
      - name: Get All Changed Files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'csv'
      - run: |
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          for added_modified_file in "${added_modified_files[@]}"; do
            echo "Do something with this ${added_modified_file}."
          done
                 
